
import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
// import { GeistMono } from 'geist/font/mono'; // Removed as per previous fix for module not found
import './globals.css';
import { ThemeProvider } from '@/contexts/theme-provider';
import { AuthProvider } from '@/contexts/auth-provider';
import { Toaster as SonnerToaster } from 'sonner'; // Updated import
import { projectConfig } from '@/config/project.config';

// Static metadata using appName from projectConfig
export const metadata: Metadata = {
  title: projectConfig.appName || 'Genesis Template', // Fallback if appName is not in config
  description: `A dynamic project template powered by Next.js, Tailwind CSS, and shadcn/ui. Generated by Firebase Studio.`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${GeistSans.variable} font-sans antialiased flex flex-col min-h-screen`}> {/* Removed GeistMono variable */}
        <ThemeProvider
          storageKey="genesis-theme"
          defaultTheme="system"
        >
          <AuthProvider>
            {children}
            <SonnerToaster richColors closeButton /> {/* Added SonnerToaster */}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
